import {
  LayoutDashboard,
  ArrowLeftRight,
  ArrowRightLeft,
  Wallet,
  CreditCard,
  Tags,
  Users,
  UserCircle2,
  Sprout,
  PawPrint,
  FileSignature,
  HardHat,
  CalendarClock,
  Landmark,
  Receipt,
  LineChart,
  ShieldCheck,
  Car,
  Stethoscope,
  Inbox,
  Bell,
  BellRing,
  BarChart3,
  Building2,
  Settings,
} from "lucide-react";
import type { IconName } from "./nav-config";

const MAP: Record<IconName, React.ComponentType<{ className?: string }>> = {
  dashboard: LayoutDashboard,
  transactions: ArrowLeftRight,
  transfers: ArrowRightLeft,
  accounts: Wallet,
  cards: CreditCard,
  categories: Tags,
  contacts: Users,
  members: UserCircle2,
  crops: Sprout,
  livestock: PawPrint,
  leases: FileSignature,
  workers: HardHat,
  wages: CalendarClock,
  loans: Landmark,
  "card-emi": Receipt,
  investments: LineChart,
  insurance: ShieldCheck,
  vehicles: Car,
  medical: Stethoscope,
  reminders: Bell,
  notifications: BellRing,
  inbox: Inbox,
  reports: BarChart3,
  workspace: Building2,
  settings: Settings,
};

export function NavIcon({ name, className }: { name: IconName; className?: string }) {
  const Icon = MAP[name];
  return <Icon className={className} />;
}
