-- CreateEnum
CREATE TYPE "UtilityBillCycle" AS ENUM ('MONTHLY', 'BIMONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'YEARLY');

-- CreateEnum
CREATE TYPE "UtilityAmountMode" AS ENUM ('FIXED', 'VARIABLE');

-- AlterEnum
ALTER TYPE "NotificationKind" ADD VALUE 'PAYMENT_FAILED';

-- AlterTable
ALTER TABLE "UtilityBill" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "estimated" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "UtilityProvider" ADD COLUMN     "amountMode" "UtilityAmountMode" NOT NULL DEFAULT 'VARIABLE',
ADD COLUMN     "autoPayLeadDays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "billingCycle" "UtilityBillCycle" NOT NULL DEFAULT 'MONTHLY',
ADD COLUMN     "billingDay" INTEGER,
ADD COLUMN     "defaultAmount" DECIMAL(14,2),
ADD COLUMN     "nextBillDate" DATE,
ADD COLUMN     "recurring" BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE INDEX "UtilityProvider_recurring_nextBillDate_idx" ON "UtilityProvider"("recurring", "nextBillDate");
